version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: p2p-redis
    ports:
      - "6379:6379"

  p2p-app:
    build: .
    container_name: p2p-peer
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./messages.db:/app/messages.db  
